version: "3.0"
services:
  ubnutu:
    build: .
    volumes:
      - ../workspace:/root/workspace
      - ./.vimrc:/root/.vimrc
    image: test_name:test_tag
    ports:
      - 22:22
    container_name: test_container
